spring.application.name=account-service

# --- Banco de Dados (MySQL) ---
spring.datasource.url=jdbc:mysql://localhost:3306/account?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Out@2025
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- Docker Compose ---
spring.docker.compose.enabled=false

# --- Configurações do RabbitMQ (Conexão) ---
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# --- Spring Cloud Stream / RabbitMQ Cloud ---
# Mapeia o binding 'warning' para a exchange 'warning-exchange'
spring.cloud.stream.bindings.warning-out-0.destination=warning-exchange
spring.cloud.stream.bindings.warning-out-0.content-type=application/json

# Configurações específicas do Binder RabbitMQ
# O 'required-groups' garante que a fila não se perca se o serviço cair
spring.cloud.stream.rabbit.bindings.warning-out-0.producer.delayed-exchange=false
spring.cloud.stream.rabbit.bindings.warning-out-0.producer.routing-key-expression='warning-key'