# --- Configurações de Servidor (RAIZ DO ARQUIVO) ---
server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always

# --- Configurações do Spring ---
spring:
  application:
    name: accountservice

  # --- Banco de Dados (MySQL) ---
  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "Out@2025"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # --- Docker ---
  docker:
    compose:
      enabled: false

  # --- Mensageria (RabbitMQ) ---
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  # --- Spring Cloud Stream ---
  cloud:
    stream:
      bindings:
        warning-out-0:
          destination: warning-exchange
          content-type: application/json
      rabbit:
        bindings:
          warning-out-0:
            producer:
              delayed-exchange: false
              routing-key-expression: "'warning-key'"