# --- Configurações de Servidor (RAIZ DO ARQUIVO) ---
server:
  port: 8082
  error:
    include-stacktrace: never
    include-message: always

# --- Configurações do Spring ---
spring:
  application:
    name: accountservice

  # --- Banco de Dados (MySQL) ---
  datasource:
    url: jdbc:mysql://localhost:3306/account?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: "Out@2025"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  # --- Docker ---
  docker:
    compose:
      enabled: false
